fix k8s api (list_node) when specifying zone
If you specify the command like:

 f4i.py add-thingvisor -y thingVisor-helloWorld.yaml -z Earth

you got an error.

Traceback (most recent call last):
  File "/app/master-controller.py", line 977, in recv_addThingVisor
    deploy_zone, available_zones = get_deploy_zone(tv_zone)  # receive {"zone":zone_tv, "gw":floatingIP} if zone exists, otherwise none
  File "/app/master-controller.py", line 559, in get_deploy_zone_on_kubernetes
    available_zones = k8s.list_available_node_zone()
  File "/app/kubernetes_functions.py", line 152, in list_available_node_zone
    api_response = api_instance.list_node()
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api/core_v1_api.py", line 13726, in list_node
    (data) = self.list_node_with_http_info(**kwargs)  # noqa: E501
  (snip)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 295, in __deserialize
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/models/v1_container_image.py", line 75, in names
    raise ValueError("Invalid value for `names`, must not be `None`")  # noqa: E501
ValueError: Invalid value for `names`, must not be `None`

- related information
https://github.com/kubernetes-client/python/issues/895

Because I'm using containerd as a CRI (Container Runtime Interface), it
might trigger this issue.

This commit adds a workaround for this error.

Signed-off-by: Hajime Tazaki <thehajime@gmail.com>